---
name: PR Greetings

on: [pull_request_target]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/first-interaction@2d4393e6bc0e2efb2e48fba7e06819c3bf61ffc9  # v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: >+
            Thank you for opening your first PR into Matplotlib!


            If you have not heard from us in a week or so, please leave a new
            comment below and that should bring it to our attention.
            Most of our reviewers are volunteers and sometimes things fall
            through the cracks.


            You can also join us [on
            gitter](https://gitter.im/matplotlib/matplotlib) for real-time
            discussion.


            For details on testing, writing docs, and our review process,
            please see [the developer
            guide](https://matplotlib.org/devdocs/devel/index.html)


            We strive to be a welcoming and open project. Please follow our
            [Code of
            Conduct](https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md).
